// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import { identity } from "../models";
import { discovery } from "../models";

export function GetIdentity(): Promise<identity.Public>;

export function GetNodeID(): Promise<string>;

export function GetPeers(): Promise<Array<discovery.Peer>>;
