// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetIdentity() {
  return window["go"]["main"]["App"]["GetIdentity"]();
}

export function GetNodeID() {
  return window["go"]["main"]["App"]["GetNodeID"]();
}

export function GetPeers() {
  return window["go"]["main"]["App"]["GetPeers"]();
}
